config/routes.rb
Spree::Core::Engine.routes.draw do
  post 'amazon/fps' => 'amazon#fps'
  post 'amazon/ipn' => 'amazon#ipn'
  get 'amazon/complete' => 'amazon#complete'
  get 'amazon/abort' => 'amazon#abort'

  namespace :admin do
  	resources :orders, only: [] do
  		resources :payments, only: [] do
  			member do
  				get 'amazon_refund'
  				post 'amazon_refund'
  			end
  		end
  	end
  end
end

app/views/spree/admin/payments/amazon_refund.html.erb
<%= render partial: 'spree/admin/shared/order_tabs', locals: { current: 'Payments' } %>

<% content_for :page_title do %>
  <i class="icon-arrow-right"></i>
  <%= link_to Spree.t(:payments), admin_order_payments_path(@order) %>
  <i class="icon-arrow-right"></i>
  <%= payment_method_name(@payment) %>
  <i class="icon-arrow-right"></i>
  <span>Refund</span>
<% end %>

<%= form_tag amazon_refund_admin_order_payment_path(@order, @payment) do %>
  <div class='label-block left five columns alpha'>
    <div>
      <fieldset data-hook="admin_variant_new_form">
        <legend><%= 'Refund' %></legend>
        <div class='field'>
          <%= label_tag 'refund_amount', 'Amount' %>
          <small><em><%= @payment.display_amount %></em></small><br>
          <% symbol = ::Money.new(1, Spree::Config[:currency]).symbol %>
          <% if Spree::Config[:currency_symbol_position] == "before" %>
            <%= symbol %><%= text_field_tag 'refund_amount', @payment.amount %>
          <% else %>
            <%= text_field_tag 'refund_amount', @payment.amount %><%= symbol %>
          <% end %>
        </div>
        <%= button 'Refund', 'icon-dollar' %>
      </fieldset>
    </div>
  </div>
<% end %>